---
  - name: Add PHP 7 PPA repository
    become: true
    apt_repository:
      repo: 'ppa:ondrej/php'

  - name: Install PHP packages
    become: true
    apt:
      name:
        - php7.3-cli
        - php7.3-curl
        - php7.3-fpm
        - php7.3-intl
        - php7.3-mysql
        - php7.3-xml
        - php7.3-mbstring
      state: latest
    notify: Restart PHP-FPM

  - name: Set date.timezone for CLI
    become: true
    lineinfile:
      dest: /etc/php/7.3/cli/php.ini
      regexp: "date.timezone ="
      line: "date.timezone = UTC"
    notify: Restart PHP-FPM

  - name: Set date.timezone for FPM
    become: true
    lineinfile:
      dest: /etc/php/7.3/fpm/php.ini
      regexp: "date.timezone ="
      line: "date.timezone = UTC"
    notify: Restart PHP-FPM